# build in Google Build with: gcloud builds submit --config backend-cloudbuild.yaml
# then deploy to Google Cloud Run with: gcloud beta run services replace ./google_cloud_run/backend.yaml --platform managed --region europe-west3

steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=eu.gcr.io/quick-heaven-279220/backend'
  - '--file=./Dockerfile.backend'
  - .

images:
- 'eu.gcr.io/quick-heaven-279220/backend'
