# This configuration is primarily for easy testing and documents how this app can be deployed.
# Start it with: `docker-compose up`
version: '3'

services:
  reverse-proxy:
    image: nginx:1.19.1
    ports:
      - 80:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    expose:
      - 8050
    environment:
      - BACKEND_URL=backend
      - BACKEND_PORT=8000
      - GUNICORN_WORKERS=2
      - GUNICORN_ACCESSLOG=-
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - 8000
    environment:
      - JWT_SECRET_KEY=SECRET-KEY
      - DB_URL=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=passwd
      - DB_DATABASE=postgres
      - GUNICORN_WORKERS=1
      - GUNICORN_ACCESSLOG=-
    depends_on:
      - database

  database:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432  # this is for external access to the database, DO NOT USE THIS FOR PRODUCTION
    environment:
      - POSTGRES_PASSWORD=passwd

