FROM python:3.7.2-alpine3.9

WORKDIR /app/backend

COPY backend requirements.txt

RUN apk add --no-cache libc-dev python3-dev g++ openssl-dev libffi-dev && pip install -r requirements.txt

EXPOSE 8000

COPY . /app

ENTRYPOINT ["/usr/local/bin/gunicorn", "--config", "config/gunicorn.conf", "--log-config", "config/logging.conf", "-b", ":8000", "wsgi:app"]
