FROM python:3.8.5-slim-buster

WORKDIR /app

COPY backend/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

COPY ./backend/ /app

RUN useradd -m backend
USER backend

ENTRYPOINT ["/usr/local/bin/gunicorn", "--worker-class", "gevent", "--preload", "--config", "config/gunicorn.py", "--log-config", "config/logging.conf", "--bind", ":8000", "wsgi:app"]
