# This configuration is primarily for easy testing and documents how this app can be deployed.
# Start it with: `docker-compose up`
version: '3'

services:
  reverse-proxy:
    image: nginx:1.19.0
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - weather-frontend

  weather-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - DBBASEDIR=/opt/dbdir
      - GUNICORN_WORKERS=4
      - GUNICORN_ACCESSLOG=-
    volumes:
       - ./frontend/test_data:/opt/dbdir
