GET http://35.217.60.27:8050/api/v1/user
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTQ1NzQyNzUsIm5iZiI6MTU5NDU3NDI3NSwianRpIjoiZmJjNjAwNjEtOWY4ZS00YTlkLThlYjktZTgxY2FkYzIwNGNlIiwiZXhwIjoxNTk0NjEwMjc1LCJpZGVudGl0eSI6ImFkbWluIiwiZnJlc2giOnRydWUsInR5cGUiOiJhY2Nlc3MiLCJ1c2VyX2NsYWltcyI6eyJyb2xlIjoiQURNSU4ifX0.LWAd6m-XeI_nrJgC88KW0XM-z3Blu2-8G76h8RDwCAw
