PUT http://35.217.32.244:8050/api/v1/user/2
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTU4NjI4NTIsIm5iZiI6MTU5NTg2Mjg1MiwianRpIjoiODkxNDIwYjEtNWU4Yi00Njg5LWJmODctZGQyZGJlMjM1MGNiIiwiZXhwIjoxNTk1ODY2NDUyLCJpZGVudGl0eSI6ImRlZmF1bHRfYWRtaW4iLCJmcmVzaCI6dHJ1ZSwidHlwZSI6ImFjY2VzcyIsInVzZXJfY2xhaW1zIjp7InN0YXRpb25faWQiOm51bGwsInJvbGUiOiJBRE1JTiJ9fQ.eOzp0brKkAsatjEFEClYecTJ94WxH_GLmL_9KRxe7p0

{
  "name": "user1",
  "password": "new password",
  "role": "PUSH_USER",
  "station_id": "SOL"
}