apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${BACKEND_SERVICE_NAME}
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: ${GCP_PROJECT_ID}:${SQL_DATABASE_ID}
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: ${BACKEND_SERVICE_ACCOUNT_NAME}
      containers:
      - image: ${GCP_CONTAINER_REGISTRY}/${GCP_PROJECT_ID}/${BACKEND_SERVICE_NAME}:${CI_COMMIT_SHA}
        env:
        - name: RUNNING_ON_SERVER
          value: 'True'
        - name: DB_INSTANCE_CONNECTION_NAME
          value: ${GCP_PROJECT_ID}:${SQL_DATABASE_ID}
        - name: DB_USER_DB_USER
          value: userdb
        - name: DB_WEATHER_DB_USER
          value: weatherdatadb
        - name: DB_USER_DATABASE
          value: users
        - name: DB_WEATHER_DATABASE
          value: weatherdata
        - name: DB_USER_DB_PASSWORD_SECRET
          value: user-db-password
        - name: DB_USER_DB_PASSWORD_SECRET_VERSION
          value: '1'
        - name: DB_WEATHER_DB_PASSWORD_SECRET
          value: weather-db-password
        - name: DB_WEATHER_DB_PASSWORD_SECRET_VERSION
          value: '1'
        - name: JWT_SECRET_KEY_SECRET
          value: jwt-secret-key
        - name: JWT_SECRET_KEY_SECRET_VERSION
          value: '1'
        - name: GUNICORN_WORKERS
          value: '1'
        - name: GUNICORN_ACCESSLOG
          value: '-'
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
