#  Remote Weather Access - Client/server solution for distributed weather networks
#   Copyright (C) 2013-2023 Ralf Rettig (info@personalfme.de)
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${BACKEND_SERVICE_NAME}
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: ${GCP_PROJECT_ID}:${SQL_DATABASE_ID}
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: ${BACKEND_SERVICE_ACCOUNT_NAME}
      containers:
        - image: ${GCP_ARTIFACT_REGISTRY}/${GCP_PROJECT_ID}/${DOCKER_REPOSITORY}/${BACKEND_SERVICE_NAME}:${CI_COMMIT_SHA}
          env:
            - name: RUNNING_ON_SERVER
              value: 'True'
            - name: DB_INSTANCE_CONNECTION_NAME
              value: ${GCP_PROJECT_ID}:${SQL_DATABASE_ID}
            - name: DB_USER_DB_USER
              value: userdb
            - name: DB_WEATHER_DB_USER
              value: weatherdatadb
            - name: DB_USER_DATABASE
              value: users
            - name: DB_WEATHER_DATABASE
              value: weatherdata
            - name: DB_USER_DB_PASSWORD_SECRET
              value: user-db-password
            - name: DB_USER_DB_PASSWORD_SECRET_VERSION
              value: 'latest'
            - name: DB_WEATHER_DB_PASSWORD_SECRET
              value: weather-db-password
            - name: DB_WEATHER_DB_PASSWORD_SECRET_VERSION
              value: 'latest'
            - name: JWT_SECRET_KEY_SECRET
              value: jwt-secret-key
            - name: JWT_SECRET_KEY_SECRET_VERSION
              value: 'latest'
            - name: GUNICORN_WORKERS
              value: '1'
            - name: GUNICORN_ACCESSLOG
              value: '-'
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
