# deploy with: gcloud beta run services replace frontend.yaml --platform managed --region europe-west3
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${FRONTEND_SERVICE_NAME}
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: ${FRONTEND_SERVICE_ACCOUNT_NAME}
      containers:
      - image: ${GCP_CONTAINER_REGISTRY}/${GCP_PROJECT_ID}/${FRONTEND_SERVICE_NAME}:${CI_COMMIT_SHA}
        env:
        - name: BACKEND_URL
          value: ${BACKEND_URL_BASE}
        - name: BACKEND_PORT
          value: '${BACKEND_PORT}'
        - name: BACKEND_DO_USE_HTTPS
          value: 'True'
        - name: GUNICORN_WORKERS
          value: '1'
        - name: GUNICORN_ACCESSLOG
          value: '-'
        - name: BRAND_NAME
          value: ${BRAND_NAME}
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
