# deploy with: gcloud beta run services replace backend.yaml --platform managed --region europe-west3
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: quick-heaven-279220:europe-west3:weatherdata
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: weather-backend@quick-heaven-279220.iam.gserviceaccount.com
      containers:
      - image: eu.gcr.io/quick-heaven-279220/backend:latest
        env:
        - name: RUNNING_ON_SERVER
          value: 'True'
        - name: DB_INSTANCE_CONNECTION_NAME
          value: quick-heaven-279220:europe-west3:weatherdata
        - name: DB_USER_DB_USER
          value: userdb
        - name: DB_WEATHER_DB_USER
          value: weatherdatadb
        - name: DB_USER_DATABASE
          value: users
        - name: DB_WEATHER_DATABASE
          value: weatherdata
        - name: DB_USER_DB_PASSWORD_SECRET
          value: user-db-password
        - name: DB_USER_DB_PASSWORD_SECRET_VERSION
          value: '1'
        - name: DB_WEATHER_DB_PASSWORD_SECRET
          value: weather-db-password
        - name: DB_WEATHER_DB_PASSWORD_SECRET_VERSION
          value: '1'
        - name: JWT_SECRET_KEY_SECRET
          value: jwt-secret-key
        - name: JWT_SECRET_KEY_SECRET_VERSION
          value: '1'
        - name: GUNICORN_WORKERS
          value: '1'
        - name: GUNICORN_ACCESSLOG
          value: '-'
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
