# TODO: is this run regularly???
# TODO: see there: https://hub.docker.com/r/sjenning/kube-nginx-letsencrypt/
apiVersion: v1
kind: Service
metadata:
  name: letsencrypt
  labels:
    app.kubernetes.io/name: weather-app
    app.kubernetes.io/instance: weather-app-12345
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: letsencrypt
    app.kubernetes.io/part-of: nginx
    app.kubernetes.io/managed-by: helm
spec:
  selector:
      app.kubernetes.io/name: weather-app
      app.kubernetes.io/instance: weather-app-12345
      tier: letsencrypt
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-certs
type: Opaque
---
apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt-job
  labels:
    app.kubernetes.io/name: weather-app
    app.kubernetes.io/instance: weather-app-12345
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: letsencrypt
    app.kubernetes.io/part-of: nginx
    app.kubernetes.io/managed-by: helm
spec:
  template:
    metadata:
      name: letsencrypt
      labels:
        app.kubernetes.io/name: weather-app
        app.kubernetes.io/instance: weather-app-12345
        tier: letsencrypt
    spec:
      containers:
        - name: letsencrypt
          image: sjenning/kube-nginx-letsencrypt:0.8.1-1
          imagePullPolicy: Always
          ports:
            - name: letsencrypt
              containerPort: 80
          env:
            - name: DOMAINS
              value: radixproductions.srvnds.de
            - name: EMAIL
              value: meteoradix@gmx.net
            - name: SECRET
              value: letsencrypt-certs
            - name: DEPLOYMENT
              value: nginx-ingress-controller
      restartPolicy: Never