apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app.kubernetes.io/name: weather-app
    app.kubernetes.io/instance: weather-app-12345
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: nginx
    app.kubernetes.io/managed-by: helm
data:
  default.conf: |
    #upstream letsencrypt {
    #  server letsencrypt:80 max_fails=0 fail_timeout=1s;
    #}

    server {
      # the TLS-termination happens in the Ingress
      listen 80;
      listen [::]:80;
      server_name _;

      location / {
        root /usr/share/nginx/html;
      }

      #location ^~ /.well-known/acme-challenge/ {
      #  proxy_pass http://letsencrypt;
      #}
    }

