#!/bin/sh
# prerm script for nest
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
	remove|upgrade|deconfigure)
		# Stop the daemon
		if [ -d /run/systemd/system ]; then
			if deb-systemd-helper --quiet is-enabled remote-weather-access.service; then
				deb-systemd-invoke stop remote-weather-access.service >/dev/null
			fi
		fi

		# Remove all Python cache directories
		pyclean -p python3-remote-weather-access
		;;
	failed-upgrade)
		;;
	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
