#!/bin/sh
# postinst script for test
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


USER="weather-daemon"
PACKAGE="remote-weather-access"
DAEMON="weatherserver.service"


# source debconf library
. /usr/share/debconf/confmodule

# Source dbconfig-common functions
if [ -f /usr/share/dbconfig-common/dpkg/postinst.pgsql  ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.pgsql
fi

case "$1" in

	configure)
		# create a new user (if not already existing)
		adduser --system --disabled-password --disabled-login --quiet --no-create-home --home /var/empty --group ${USER}

		# change the owner of the directories created in preinst
		if id -u $USER > /dev/null 2>&1; then    
			chown ${USER}:${USER} /var/log/${PACKAGE}
			chown -R ${USER}:${USER} /var/lib/${PACKAGE}
			chmod -R 0777 /var/lib/${PACKAGE}/templates
		fi
	
		# set up the daemon
		deb-systemd-helper unmask ${DAEMON} >/dev/null || true

		if deb-systemd-helper --quiet was-enabled ${DAEMON}; then
			deb-systemd-helper enable ${DAEMON} >/dev/null || true
		else
			deb-systemd-helper update-state ${DAEMON} >/dev/null || true
		fi

		if [ -d /run/systemd/system ]; then
			systemctl --system daemon-reload >/dev/null || true
			deb-systemd-invoke start ${DAEMON} >/dev/null || true
		fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0
		;;

  *)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;

esac

db_stop

exit 0
